name: Cache Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set cache key
        id: vars
        run: echo "key=fw-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Download firmware
        run: |
          mkdir -p FIRMWARE

          echo "Downloading A34 firmware..."
          wget -O FIRMWARE/A34.zip \
          "https://h3cked.qzz.io/d/H3CKED_HDD/H3CKED_UI/H3CKED-UI/H3CKED-UI/BASE_FW/A346B.zip?sign=9gauBSBCS3nS6wu10PILcEVoIuVd8qNGojO5Y6aeb48=:0"

          echo "Downloading A24 firmware..."
          wget -O FIRMWARE/A24.zip \
          "https://h3cked.qzz.io/d/H3CKED_HDD/H3CKED_UI/H3CKED-UI/H3CKED-UI/BASE_FW/A245F.zip?sign=LnH18kouVWJ0vz5Se2mDQGNDYyX4nZ1uOXpIWQOt1ck=:0"

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: FIRMWARE
          key: ${{ steps.vars.outputs.key }}
